=== KongkongNT15/KLibReference/src/xml/Schema/CppPage.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:include schemaLocation="BaseSchema.xsd" />

	<xs:simpleType name="FuncDefType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Default" />
			<xs:enumeration value="Deleted" />
			<xs:enumeration value="Defined" />
		</xs:restriction>
	</xs:simpleType>

	<!-- 型の修飾子 -->
	<xs:simpleType name="TypeQualifier">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ConstLValueReference" />	<!-- T const& -->
			<xs:enumeration value="ConstPointer" />			<!-- const T* -->
			<xs:enumeration value="LValueReference" />		<!-- T& -->
			<xs:enumeration value="RValueReference" />		<!-- T&& -->
			<xs:enumeration value="Pointer" />				<!-- T* -->
			<xs:enumeration value="Unqualified" />			<!-- T -->
		</xs:restriction>
	</xs:simpleType>

	<!-- 演算子の種類 -->
	<xs:simpleType name="OperatorType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Assignment" />         <!-- = (単純代入) -->
			<xs:enumeration value="AddAssignment" />      <!-- += (複合代入) -->
			<xs:enumeration value="SubtractAssignment" /> <!-- -= -->
			<xs:enumeration value="MultiplyAssignment" /> <!-- *= -->
			<xs:enumeration value="DivideAssignment" />   <!-- /= -->
			<xs:enumeration value="ModuloAssignment" />   <!-- %= -->
			<xs:enumeration value="BitwiseANDAssignment" />   <!-- &amp;= -->
			<xs:enumeration value="BitwiseORAssignment" /><!-- |= マイナーな複合代入 -->
			<xs:enumeration value="BitwiseXORAssignment" />   <!-- ^= マイナーな複合代入 -->
			<xs:enumeration value="LeftShiftAssignment" /><!-- &lt;&lt;= -->
			<xs:enumeration value="RightShiftAssignment" />   <!-- &gt;&gt;= -->
			<xs:enumeration value="Addition" />           <!-- + (二項) -->
			<xs:enumeration value="Subtraction" />        <!-- - (二項) -->
			<xs:enumeration value="Multiplication" />     <!-- * (二項) -->
			<xs:enumeration value="Division" />           <!-- / -->
			<xs:enumeration value="Modulo" />             <!-- % -->
			<xs:enumeration value="Equal" />              <!-- == -->
			<xs:enumeration value="NotEqual" />           <!-- != -->
			<xs:enumeration value="LessThan" />           <!-- &lt; -->
			<xs:enumeration value="GreaterThan" />        <!-- &gt; -->
			<xs:enumeration value="LessEqual" />          <!-- &lt;= -->
			<xs:enumeration value="GreaterEqual" />       <!-- &gt;= -->
			<xs:enumeration value="ThreeWayComparison" />   <!-- &lt;=&gt; (C++20: 宇宙船演算子) -->
			<xs:enumeration value="LogicalAND" />         <!-- &amp;&amp; -->
			<xs:enumeration value="LogicalOR" />          <!-- || -->
			<xs:enumeration value="LogicalNOT" />         <!-- ! -->
			<xs:enumeration value="BitwiseAND" />         <!-- &amp; (二項) -->
			<xs:enumeration value="BitwiseOR" />          <!-- | operator|() -->
			<xs:enumeration value="BitwiseXOR" />         <!-- ^ operator^() -->
			<xs:enumeration value="LeftShift" />          <!-- &lt;&lt; (ストリーム演算子としてもよく使われる) -->
			<xs:enumeration value="RightShift" />         <!-- &gt;&gt; (ストリーム演算子としてもよく使われる) -->
			<xs:enumeration value="BitwiseNOT" />         <!-- ~ (単項) -->
			<xs:enumeration value="AddressOf" />          <!-- &amp; (アドレス取得) -->
			<xs:enumeration value="Dereference" />        <!-- * (間接参照/デリファレンス) -->
			<xs:enumeration value="PrefixIncrement" />    <!-- ++ (前置インクリメント) -->
			<xs:enumeration value="PostfixIncrement" />   <!-- ++ (後置インクリメント) -->
			<xs:enumeration value="PrefixDecrement" />    <!-- (前置デクリメント) -->
			<xs:enumeration value="PostfixDecrement" />   <!-- (後置デクリメント) -->
			<xs:enumeration value="UnaryPlus" />          <!-- + (単項プラス) -->
			<xs:enumeration value="UnaryMinus" />         <!-- - (単項マイナス) -->
			<xs:enumeration value="Subscript" />          <!-- [] (添字演算子) -->
			<xs:enumeration value="FunctionCall" />       <!-- () (関数呼び出し演算子) -->
			<xs:enumeration value="MemberAccessPointer" /><!-- -> (メンバアクセス演算子/アロー演算子) -->
			<xs:enumeration value="Comma" />              <!--  /> (コンマ演算子) -->
			<xs:enumeration value="TernaryConditional" /> <!-- ?: (条件演算子) -->
			<xs:enumeration value="New" />                <!-- new (メモリ確保) -->
			<xs:enumeration value="Delete" />             <!-- delete (メモリ解放) -->
			<xs:enumeration value="SizeOf" />             <!-- sizeof (サイズ取得) -->
			<xs:enumeration value="TypeID" />             <!-- typeid (型情報取得) -->
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="ParameterType">
		<xs:sequence>
			<xs:element name="Type" type="TemplateSpecializationType" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="Name" type="xs:string" use="required" />
		<xs:attribute name="Description" type="xs:string" use="required" />
		<xs:attribute name="TypeQualifier" type="TypeQualifier" default="Unqualified" />
	</xs:complexType>

	<xs:complexType name="TemplateParameterType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="Name" type="xs:string" use="required" />
				<xs:attribute name="Description" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="TemplateSpecializationType">
		<xs:choice minOccurs="1" maxOccurs="unbounded">
			<xs:element name="Type" >
				<xs:complexType>
					<xs:attribute name="Name" type="xs:string" use="required" />
				</xs:complexType>
			</xs:element>
			<xs:element name="TypeSpecialization" type="TemplateSpecializationType" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		<xs:attribute name="Name" type="xs:string" use="required" />
		<xs:attribute name="TypeQualifier" type="TypeQualifier" default="Unqualified" use="optional" />
	</xs:complexType>

	<xs:element name="TypeSpecialization" type="TemplateSpecializationType" />

	<xs:element name="Parameter" type="ParameterType" />
	<xs:element name="TemplateParameter" type="TemplateParameterType" />

	<xs:element name="Parameters">
		<xs:complexType>
			<xs:choice minOccurs="1">
				<xs:element ref="Parameter" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="TemplateParameters">
		<xs:complexType>
			<xs:choice minOccurs="1">
				<xs:element ref="TemplateParameter" />
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="FunctionType">
		<xs:attribute name="Path" type="xs:string" use="optional" />
		<xs:attribute name="Type" type="FuncDefType" default="Default" use="optional" />
		<xs:attribute name="Name" type="xs:string" use="optional" />
		<xs:attribute name="Description" use="optional" />
	</xs:complexType>
	
	<!-- メンバー関数がconstかstaticか -->
	<xs:simpleType name="MemberFunctionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Const" />
			<xs:enumeration value="Normal" />
			<xs:enumeration value="Static" />
		</xs:restriction>
	</xs:simpleType>

	<!-- 仮想関数定義 -->
	<xs:simpleType name="MemberFunctionVirtualType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NonVirtual" />
			<xs:enumeration value="PureVirtual" />
			<xs:enumeration value="Virtual" />
		</xs:restriction>
	</xs:simpleType>

	<!-- constexpr, consteval 修飾子 -->
	<xs:simpleType name="FunctionConstexprSpecifier">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Constexpr" />
			<xs:enumeration value="Consteval" />
			<xs:enumeration value="None" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="FunctionAttributeType">
		<xs:attribute name="ConstexprSpecifier" type="FunctionConstexprSpecifier" default="None" use="optional" />
		<xs:attribute name="Nodiscard" type="xs:boolean" default="false" use="optional" />
		<xs:attribute name="Noexcept" type="xs:boolean" default="false" use="optional" />
	</xs:complexType>

	<xs:element name="Type" >
		<xs:complexType>
			<xs:attribute name="ClassName" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="Returns">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Type" type="TemplateSpecializationType" minOccurs="0" />
				<xs:element name="Description" type="TextBlockType" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Constructors">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DefaultConstructor" type="FunctionType" />
				<xs:element name="CopyConstructor" type="FunctionType" />
				<xs:element name="MoveConstructor" type="FunctionType" />
				<xs:element name="Constructor" type="FunctionType" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Destructor" >
		<xs:complexType>
			<xs:attribute name="Description" use="optional" />
			<xs:attribute name="Uri" use="optional" />
			<xs:attribute name="Type" type="FuncDefType" default="Default" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="Operators">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CopyOperator" type="FunctionType" />
				<xs:element name="MoveOperator" type="FunctionType" />
				<xs:element name="Operator" type="FunctionType" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="FunctionsType">
		<xs:sequence>
			<xs:element name="Function" type="FunctionType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="FunctionExampleType">
		<xs:sequence>
			<xs:element name="Description" type="TextBlockType" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="Path" type="xs:string" default="ex.cpp" use="optional" />
	</xs:complexType>

	<xs:complexType name="EnumMemberType">
		<xs:attribute name="Name" type="xs:string" use="required" />
		<xs:attribute name="Description" type="xs:string" use="required" />
		<xs:attribute name="Value" type="xs:integer" use="required" />
	</xs:complexType>

	<xs:element name="EnumMember" type="EnumMemberType" />

	<!-- 列挙型の説明ページ -->
	<xs:element name="EnumPage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Description" type="TextBlockType" />
				<xs:element name="Members">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="EnumMember" minOccurs="1" maxOccurs="unbounded" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Name" type="xs:string" use="required" />
			<xs:attribute name="IsEnumClass" type="xs:boolean" default="false" use="optional" />
		</xs:complexType>
	</xs:element>

	<!-- 関数説明のページ -->
	<xs:element name="FunctionPage">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="TemplateParameters" minOccurs="0" />
				<xs:element ref="Parameters" minOccurs="0" />
				<xs:element name="Description" type="TextBlockType" />
				<xs:element ref="Returns" />
				<xs:element name="Remarks" type="TextBlockType" minOccurs="0" />
				<xs:element name="Example" type="FunctionExampleType" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="ConstexprSpecifier" type="FunctionConstexprSpecifier" default="None" use="optional" />
			<xs:attribute name="IsStatic" type="xs:boolean" default="false" use="optional" />
			<xs:attribute name="Name" type="xs:string" use="required" />
			<xs:attribute name="Nodiscard" type="xs:boolean" default="false" use="optional" />
			<xs:attribute name="Noexcept" type="xs:boolean" default="false" use="optional" />
		</xs:complexType>
	</xs:element>

	<!-- メンバー関数説明のページ -->
	<xs:element name="MethodPage">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="TemplateParameters" minOccurs="0" />
				<xs:element ref="Parameters" minOccurs="0" />
				<xs:element name="Description" type="TextBlockType" />
				<xs:element ref="Returns" />
				<xs:element name="Remarks" type="TextBlockType" minOccurs="0" />
				<xs:element name="Example" type="FunctionExampleType" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="ClassName" type="xs:string" use="optional" />
			<xs:attribute name="ConstexprSpecifier" type="FunctionConstexprSpecifier" default="None" use="optional" />
			<xs:attribute name="MethodType" type="MemberFunctionType" />
			<xs:attribute name="Name" type="xs:string" use="required" />
			<xs:attribute name="Nodiscard" type="xs:boolean" default="false" use="optional" />
			<xs:attribute name="Noexcept" type="xs:boolean" default="false" use="optional" />
			<xs:attribute name="VirtualType" type="MemberFunctionVirtualType" default="NonVirtual" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="NamespacePage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Description" type="TextBlockType" />
				<xs:element name="Classes" type="PathCollection" minOccurs="0" />
				<xs:element name="Structures" type="PathCollection" minOccurs="0" />
				<xs:element name="Enumerationes" type="PathCollection" minOccurs="0" />
				<xs:element name="Functions" type="PathCollection" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="Name" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="StructPageType">
		<xs:sequence>
			<xs:element name="Description" type="TextBlockType" />
			<xs:element name="BaseClasses" type="PathCollection" minOccurs="0" />
			<xs:element ref="TemplateParameters" minOccurs="0" maxOccurs="1" />
			<xs:element name="StaticMethods" type="FunctionsType" minOccurs="0" />
			<xs:element ref="Constructors" />
			<xs:element ref="Destructor" />
			<xs:element ref="Operators" />
			<xs:element name="Methods" type="FunctionsType" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="IsFinal" type="xs:boolean" default="false" use="optional" />
		<xs:attribute name="Name" type="xs:string" use="required" />
	</xs:complexType>

	<xs:element name="ClassPage" type="StructPageType" />
	<xs:element name="StructPage" type="StructPageType" />

	<!--  -->
	<xs:element name="CppRefPage" >
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Description" type="TextBlockType" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== KongkongNT15/KLibReference/src/xml/CellSimRef/CellSim/Version/index.xml
<ClassPage
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../Schema/CppPage.xsd"
    IsFinal="true"
    Name="Version">

    <Description>CellSimのバージョン情報を提供します。</Description>

    <StaticMethods>
        <Function Path="Extension/" />
        <Function Path="Major/" />
        <Function Path="Minor/" />
        <Function Path="Patch/" />
    </StaticMethods>

    <Constructors>
        <DefaultConstructor Type="Deleted" />
        <CopyConstructor Type="Deleted" />
        <MoveConstructor Type="Deleted" />
    </Constructors>

    <Destructor Type="Deleted" />

    <Operators>
        <CopyOperator Type="Deleted" />
        <MoveOperator Type="Deleted" />
    </Operators>

</ClassPage>

=== KongkongNT15/KLibReference/src/xml/CellSimRef/2.1.2/API/CellSim/Messages/index.xml
<?xml version="1.0" encoding="utf-8" ?>

<ClassPage
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../../../Schema/CppPage.xsd"
    IsFinal="true"
    Name="Messages">

    <Description>実行時に画面に表示するメッセージを管理します。メッセージは./languagesにある言語ファイルから取得します。</Description>

    <StaticMethods>
        <Function Path="Get/" />
        <Function Path="Initialize/" />
        <Function Path="IsInitialized/" />
    </StaticMethods>

    <Constructors>
        <DefaultConstructor Type="Deleted" />
        <CopyConstructor Type="Deleted" />
        <MoveConstructor Type="Deleted" />
    </Constructors>

    <Destructor Type="Deleted" />

    <Operators>
        <CopyOperator Type="Deleted" />
        <MoveOperator Type="Deleted" />
    </Operators>

</ClassPage>
